### ISSUE TITLE
Misalignment for autotask notification metadata - Contract Sentinels

### ISSUE THREAD

**Issue by ggonzalez94** [OpenZeppelin/defender-docs#172]
## Background
When using autotask conditions with Contract Sentinels you can populate the metadata field and pass it to the autotask notification function. This is quite useful, but where to find that field is not correctly shown in the docs.

## Issue
According to the [docs](https://docs.openzeppelin.com/defender/sentinel#autotask), it shows that the metadata field should be inside the matchReasons of the event. But it is actually coming as a separate field in the event.
Here’s a [gist](https://gist.github.com/ggonzalez94/0926d33fae15a4d7c8583aead8300b28) showing the difference

**Comment by BjMrq** [comment]
Hey @ggonzalez94 thanks for raising this issue!

**Comment by ggonzalez94** [comment]
Hi @BjMrq  I see the change was already merged. Do you want me to go ahead and close the issue?

**Comment by BjMrq** [comment]
All good! Have a great Day
