### ISSUE TITLE
Broken Link on Defender Available Networks Section

### ISSUE THREAD

**Issue by xdaluca** [OpenZeppelin/defender-docs#236]
The link of "reach out to us" at the bottom of the [available networks section](https://docs.openzeppelin.com/defender/v2/#networks) is sending me to https://www.openzeppelin.com/defender-2.0-feedback and gives a 405 page not found error.

> If there is any other network or layer-2 solution you would like to use from Defender 2.0, please [reach out to us](https://www.openzeppelin.com/defender-2.0-feedback)!

**Comment by cairoeth** [comment]
Fixed in #237. Thanks!
